// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/foo/foo.proto

package proto_labs_foo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message
type Foo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_2419a9a62c73be0d, []int{0}
}
func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (dst *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(dst, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

func (m *Foo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Foo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FooRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRequest) Reset()         { *m = FooRequest{} }
func (m *FooRequest) String() string { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()    {}
func (*FooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_2419a9a62c73be0d, []int{1}
}
func (m *FooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest.Unmarshal(m, b)
}
func (m *FooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest.Marshal(b, m, deterministic)
}
func (dst *FooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest.Merge(dst, src)
}
func (m *FooRequest) XXX_Size() int {
	return xxx_messageInfo_FooRequest.Size(m)
}
func (m *FooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest proto.InternalMessageInfo

type FooResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Foo                  *Foo     `protobuf:"bytes,2,opt,name=foo" json:"foo,omitempty"`
	Foos                 []*Foo   `protobuf:"bytes,3,rep,name=foos" json:"foos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooResponse) Reset()         { *m = FooResponse{} }
func (m *FooResponse) String() string { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()    {}
func (*FooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_foo_2419a9a62c73be0d, []int{2}
}
func (m *FooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooResponse.Unmarshal(m, b)
}
func (m *FooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooResponse.Marshal(b, m, deterministic)
}
func (dst *FooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooResponse.Merge(dst, src)
}
func (m *FooResponse) XXX_Size() int {
	return xxx_messageInfo_FooResponse.Size(m)
}
func (m *FooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FooResponse proto.InternalMessageInfo

func (m *FooResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *FooResponse) GetFoo() *Foo {
	if m != nil {
		return m.Foo
	}
	return nil
}

func (m *FooResponse) GetFoos() []*Foo {
	if m != nil {
		return m.Foos
	}
	return nil
}

func init() {
	proto.RegisterType((*Foo)(nil), "proto.labs.foo.Foo")
	proto.RegisterType((*FooRequest)(nil), "proto.labs.foo.FooRequest")
	proto.RegisterType((*FooResponse)(nil), "proto.labs.foo.FooResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FooService service

type FooServiceClient interface {
	CreateFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*FooResponse, error)
	GetFoo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error)
}

type fooServiceClient struct {
	cc *grpc.ClientConn
}

func NewFooServiceClient(cc *grpc.ClientConn) FooServiceClient {
	return &fooServiceClient{cc}
}

func (c *fooServiceClient) CreateFoo(ctx context.Context, in *Foo, opts ...grpc.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := grpc.Invoke(ctx, "/proto.labs.foo.FooService/CreateFoo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) GetFoo(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := grpc.Invoke(ctx, "/proto.labs.foo.FooService/GetFoo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FooService service

type FooServiceServer interface {
	CreateFoo(context.Context, *Foo) (*FooResponse, error)
	GetFoo(context.Context, *FooRequest) (*FooResponse, error)
}

func RegisterFooServiceServer(s *grpc.Server, srv FooServiceServer) {
	s.RegisterService(&_FooService_serviceDesc, srv)
}

func _FooService_CreateFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Foo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).CreateFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.labs.foo.FooService/CreateFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).CreateFoo(ctx, req.(*Foo))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_GetFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).GetFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.labs.foo.FooService/GetFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).GetFoo(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FooService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.labs.foo.FooService",
	HandlerType: (*FooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFoo",
			Handler:    _FooService_CreateFoo_Handler,
		},
		{
			MethodName: "GetFoo",
			Handler:    _FooService_GetFoo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/foo/foo.proto",
}

func init() { proto.RegisterFile("proto/foo/foo.proto", fileDescriptor_foo_2419a9a62c73be0d) }

var fileDescriptor_foo_2419a9a62c73be0d = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x4d, 0x23, 0xab, 0x3b, 0xab, 0x7b, 0xc8, 0x5e, 0xc2, 0x7a, 0x29, 0x01, 0xb1, 0xa7,
	0x14, 0xea, 0x03, 0x78, 0x28, 0xd4, 0x7b, 0x7c, 0x82, 0xfe, 0x99, 0x48, 0x41, 0x9d, 0xda, 0x44,
	0x7d, 0x0f, 0x9f, 0x58, 0x32, 0xda, 0x83, 0x50, 0xf1, 0x10, 0xc2, 0xc7, 0x7c, 0xdf, 0x6f, 0xbe,
	0x81, 0xc3, 0x34, 0x53, 0xa4, 0xd2, 0x13, 0x3f, 0xcb, 0x4a, 0xed, 0xf9, 0xb3, 0x4f, 0x6d, 0x17,
	0xac, 0x27, 0x32, 0x25, 0xc8, 0x86, 0x48, 0xed, 0x21, 0x1b, 0x07, 0x2d, 0x72, 0x51, 0x5c, 0xba,
	0x6c, 0x1c, 0x94, 0x86, 0xb3, 0x67, 0x0c, 0xa1, 0x7d, 0x44, 0x9d, 0xe5, 0xa2, 0xd8, 0xba, 0x45,
	0x9a, 0x0b, 0x80, 0x86, 0xc8, 0xe1, 0xeb, 0x1b, 0x86, 0x68, 0x3e, 0x60, 0xc7, 0x2a, 0x4c, 0xf4,
	0x12, 0x30, 0xc5, 0xfa, 0x19, 0xdb, 0x88, 0xdf, 0xac, 0x73, 0xb7, 0x48, 0x75, 0x0d, 0xd2, 0x13,
	0x31, 0x6c, 0x57, 0x1d, 0xec, 0xef, 0x16, 0x36, 0x31, 0xd2, 0x5c, 0xdd, 0xc0, 0xa9, 0x27, 0x0a,
	0x5a, 0xe6, 0xf2, 0x2f, 0x1f, 0x1b, 0xaa, 0x4f, 0xc1, 0x3d, 0x1e, 0x70, 0x7e, 0x1f, 0x7b, 0x54,
	0x77, 0xb0, 0xad, 0x79, 0x53, 0x3a, 0x66, 0x2d, 0x76, 0xbc, 0x5a, 0x63, 0xfd, 0xf4, 0x36, 0x27,
	0xaa, 0x86, 0xcd, 0x3d, 0xc6, 0x94, 0x3e, 0xae, 0x1a, 0xf9, 0xdc, 0x7f, 0x20, 0xdd, 0x86, 0xa7,
	0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x7d, 0x13, 0x4e, 0x7a, 0x01, 0x00, 0x00,
}
